### ISSUE TITLE
Configuration is broken in 4.0.0

### ISSUE THREAD

**Issue by adejanovski** [composable-systems/dropwizard-cassandra#22]
Working on [Reaper](https://github.com/thelastpickle/cassandra-reaper) I noticed that queryOptions.consistencyLevel and queryOptions.serialConsistencyLevel were not recognized by the lib anymore in 4.0.0 while it works in 3.0.2 : 

```
java -jar target/cassandra-reaper-0.4.0-SNAPSHOT.jar server resource/cassandra-reaper-cassandra.yaml 
resource/cassandra-reaper-cassandra.yaml has an error:
  * Unrecognized field at: cassandra.queryOptions.consistencyLevel
```

After running a few more experiments, it seems like all configuration elements below level 1 aren't recognized anymore : 

```
java -jar target/cassandra-reaper-0.4.0-SNAPSHOT.jar server resource/cassandra-reaper-cassandra.yaml 
resource/cassandra-reaper-cassandra.yaml has an error:
  * Unrecognized field at: cassandra.socketOptions.connectTimeoutMillis
```

The switch to optionals in CassandraFactory seem to have broken nested configuration parsing.

**Comment by stuartgunter** [comment]
Hey. Thanks for raising this. I'm surprised it wasn't picked up by the smoke tests, as those try out every piece of configuration, including nested config.

Please could you take a look at the smoke tests and see if I've done something wrong there. I'd really like to make sure the tests are picking this sort of thing up to avoid causing problems like this again.

Once again, thanks for raising the issue! Really appreciate it.

**Comment by stuartgunter** [comment]
Just following up on this... have you had a chance to dig into the problem further? Does anything stand out to you as being incorrect in the smoke tests that can help isolate the issue?

If this is broken, I'd really like to fix it sooner rather than later.

**Comment by adejanovski** [comment]
Hi @stuartgunter,

the blame is on me : Reaper is still using Dropwizard 0.7.1, and while the smoke tests are passing with 1.0.0, they fail with 0.7.1.
I'll see how I can upgrade to 1.0.0 in Reaper but the test suite is based on HTTP client classes that aren't provided with recent versions of Cassandra, so I'll stick with dropwizard-cassandra 3.0.2 for now.

Cheers
