### ISSUE TITLE
Clarification regarding release of CassandraBundle.java

### ISSUE THREAD

**Issue by 1605200517** [composable-systems/dropwizard-cassandra#27]
According the project README, integrators should use CassandraBundle following Dropwizard framework principles.
Source code of this class: https://github.com/composable-systems/dropwizard-cassandra/blob/master/src/main/java/systems/composable/dropwizard/cassandra/CassandraBundle.java

However, it seems to be not contained in the current release 4.0.0. 

Clarification:
- since which release has it been introduced?
- will it work well with DropWizard also only with CassandraFactory or are there any risks/limitations? 
If not yet (as current snapshot is broken):
- when is the next release containing it to expect?
- how to integrate with Dropwizard in release before that and which version of Dropwizard to use?

![image](https://cloud.githubusercontent.com/assets/1834666/24836135/109dc11c-1d14-11e7-9c90-7ff47f410128.png)

**Comment by stuartgunter** [comment]
Hi

This has only very recently been merged into master from a PR (look at the commit history for details) and is due to be released shortly. Please check back in a couple of days for the latest release and let me know if you have any problems using the new features.

Thanks

**Comment by synergiator** [comment]
awesome - thanks!
