### ISSUE TITLE
Support PercentileSpeculativeExecutionPolicy

### ISSUE THREAD

**Issue by kfateem** [composable-systems/dropwizard-cassandra#28]
The `PercentileSpeculativeExecutionPolicy` has existed since Cassandra 2.x. 
Please implement `PercentileSpeculativeExecutionPolicyFactory`. 
There are various supported trackers that should be configurable:
- `PerHostPercentileTracker`
- `ClusterWidePercentileTracker`

**Comment by stuartgunter** [comment]
This was originally excluded when it was in beta, but I see it has now been promoted to a regular part of the API. If this is something you need, please submit a PR with the relevant changes.

Please also ensure that the same coding style, tests, docs, etc. are included to keep a consistent implementation across the library.

**Comment by stuartgunter** [comment]
I've not seen any activity on this, so assuming it's not required. I'm happy to accept a PR containing this feature if it's something you need.
